"""Write the example datasets to disk, for the CLI and the web app."""

from __future__ import annotations

from pathlib import Path

from ..io import write_graph
from .examples import example_pair, example_sequence, large_example_pair, perturb_labels

__all__ = ["DEMO_README", "write_demo_datasets"]

DEMO_README = """\
# graphdiff demo datasets

Generated by `graphdiff demo`; nothing here was downloaded.

| files | what | try |
| --- | --- | --- |
| snapshot_2024.graphml, snapshot_2025.graphml | small pair, 52 nodes: people, orgs, topics | A = 2024, B = 2025 |
| baseline.graphml, rebuilt.graphml | ~3,000 nodes, 28 communities; change concentrated in 3 of them | A = baseline, B = rebuilt |
| rebuilt-renamed.graphml | `rebuilt` with 10% of labels rewritten (case, suffix, separator, typo) | A = baseline, B = rebuilt-renamed, matching = **fuzzy** |
| t0.graphml … t5.graphml | six snapshots: steady drift, one event (t2→t3), a hotspot community, flickering nodes | mark t0…t5 as **T** in order |

Formats: any of GraphML, node-link JSON, CSV/TSV edge lists (`source,target[,type,weight]`),
or Parquet can be dropped into this folder and compared the same way.
"""


def write_demo_datasets(directory: str | Path, *, force: bool = False) -> list[Path]:
    """Write every example dataset into ``directory``; returns the files written.

    Existing files are left alone unless ``force`` is set, so this is safe to
    call on every start of ``graphdiff app --demo``.
    """
    directory = Path(directory)
    directory.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []

    def put(graph, name: str) -> None:  # type: ignore[no-untyped-def]
        path = directory / name
        if path.exists() and not force:
            return
        write_graph(graph, path)
        written.append(path)

    a, b = example_pair()
    put(a, "snapshot_2024.graphml")
    put(b, "snapshot_2025.graphml")
    big_a, big_b = large_example_pair()
    put(big_a, "baseline.graphml")
    put(big_b, "rebuilt.graphml")
    renamed, _ = perturb_labels(big_b, fraction=0.1, seed=2, name="rebuilt-renamed")
    put(renamed, "rebuilt-renamed.graphml")
    for snap in example_sequence():
        put(snap, f"{snap.name}.graphml")
    readme = directory / "README.md"
    if not readme.exists() or force:
        readme.write_text(DEMO_README, encoding="utf-8")
        written.append(readme)
    return written
